[package]
name = "rustyboi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
egui = "0.26"
egui-wgpu = "0.26.0"
egui-winit = { version = "0.26", default-features = false, features = ["clipboard", "links", "wayland", "x11"] }
pixels = "0.15.0"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
winit = "0.29"
winit_input_helper = "0.15"

[profile.release]
# 454744 bytes
strip = true
# 377544
opt-level = "z"
# 373448
lto = true
# 320104
