[workspace]
resolver = "2"
members = [
    "rustyboi",
    "run-wasm",
]
default-members = ["rustyboi"]

[profile.release]
# 454744 bytes
strip = true
# 377544
opt-level = "z"
# 373448
# lto = true
# 320104
