[package]
name = "rustyboi-platform"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rustyboi"
path = "src/main.rs"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "rustyboi_platform_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
rustyboi-core = { path = "../rustyboi-core" }
rustyboi-egui = { path = "../rustyboi-egui" }
egui = "0.26"
egui-wgpu = "0.26.0"
clap = { version = "4.5.48", features = ["derive"] }
log = "0.4.28"
pixels = "0.15.0"
rodio = "0.19"
serde_json = "1.0.145"
winit = "0.30.12"
winit_input_helper = "0.16.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit = { version = "0.26", default-features = false, features = ["clipboard", "links", "wayland", "x11"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
egui-winit = { version = "0.26", default-features = false, features = ["links"] }
web-sys = { version = "0.3.81", features = ["GpuTextureFormat"] }
wasm-bindgen = "0.2.104"
wasm-bindgen-futures = "0.4.54"
