use crate::{cpu, memory};

type OpcodeFn = fn(&mut cpu::SM83, &mut memory::mmio::MMIO);

pub struct Opcode {
    pub length: u8,
    pub cycles: u8,
    pub execute: OpcodeFn,
}

fn nop(_cpu: &mut cpu::SM83, _mmio: &mut memory::mmio::MMIO) {
}

pub const OPCODES: [Opcode; 256] = [
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x00
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x01
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x02
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x03
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x04
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x05
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x06
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x07
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x08
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x09
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x0A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x0B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x0C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x0D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x0E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x0F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x10
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x11
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x12
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x13
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x14
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x15
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x16
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x17
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x18
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x19
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x1A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x1B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x1C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x1D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x1E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x1F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x20
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x21
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x22
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x23
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x24
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x25
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x26
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x27
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x28
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x29
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x2A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x2B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x2C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x2D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x2E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x2F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x30
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x31
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x32
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x33
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x34
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x35
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x36
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x37
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x38
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x39
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x3A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x3B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x3C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x3D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x3E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x3F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x40
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x41
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x42
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x43
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x44
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x45
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x46
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x47
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x48
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x49
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x4A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x4B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x4C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x4D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x4E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x4F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x50
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x51
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x52
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x53
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x54
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x55
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x56
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x57
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x58
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x59
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x5A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x5B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x5C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x5D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x5E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x5F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x60
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x61
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x62
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x63
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x64
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x65
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x66
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x67
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x68
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x69
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x6A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x6B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x6C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x6D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x6E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x6F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x70
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x71
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x72
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x73
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x74
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x75
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x76
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x77
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x78
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x79
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x7A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x7B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x7C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x7D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x7E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x7F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x80
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x81
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x82
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x83
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x84
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x85
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x86
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x87
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x88
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x89
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x8A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x8B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x8C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x8D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x8E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x8F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x90
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x91
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x92
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x93
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x94
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x95
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x96
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x97
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x98
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x99
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x9A
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x9B
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x9C
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x9D
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x9E
    Opcode { length: 1, cycles: 4, execute: nop }, // 0x9F
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA0
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA1
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA2
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA3
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA4
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA5
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA6
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA7
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA8
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xA9
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xAA
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xAB
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xAC
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xAD
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xAE
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xAF
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB0
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB1
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB2
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB3
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB4
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB5
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB6
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB7
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB8
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xB9
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xBA
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xBB
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xBC
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xBD
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xBE
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xBF
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC0
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC1
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC2
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC3
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC4
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC5
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC6
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC7
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC8
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xC9
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xCA
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xCB
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xCC
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xCD
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xCE
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xCF
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD0
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD1
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD2
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD3
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD4
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD5
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD6
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD7
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD8
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xD9
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xDA
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xDB
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xDC
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xDD
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xDE
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xDF
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE0
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE1
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE2
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE3
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE4
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE5
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE6
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE7
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE8
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xE9
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xEA
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xEB
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xEC
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xED
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xEE
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xEF
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF0
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF1
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF2
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF3
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF4
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF5
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF6
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF7
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF8
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xF9
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xFA
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xFB
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xFC
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xFD
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xFE
    Opcode { length: 1, cycles: 4, execute: nop }, // 0xFF
];
